document.addEventListener("DOMContentLoaded",async()=>{
  if(!MV.auth.isAdmin())return;
  const params=new URLSearchParams(location.search);let seasonId=params.get("seasonId"),id=params.get("id");const form=document.getElementById("episodeForm"),saveBtn=document.getElementById("saveEpisode");
  let actors=[],directors=[],writers=[],season=null,episode=null,actorPicker,directorPicker,writerPicker;
  try{
    if(id&&!seasonId){episode=await MV.api.get(`episodes/${id}`);seasonId=episode.seasonId;}
    if(!seasonId){MV.ui.toast("Season id is required.","danger");location.replace("tvshows.html");return;}
    const req=[MV.api.get("actors"),MV.api.get("directors"),MV.api.get("writers"),MV.api.get(`seasons/${seasonId}`)];if(id&&!episode)req.push(MV.api.get(`episodes/${id}`));const d=await Promise.all(req);[actors,directors,writers,season]=d;if(id&&!episode)episode=d[4];
    document.getElementById("episodeFormTitle").textContent=id?`Edit Episode · Season ${season.seasonNumber}`:`Add Episode · Season ${season.seasonNumber}`;
    setupPickers();if(episode)fill(episode);setupValidation();
  }catch(err){MV.ui.showError(err);}
  function setupPickers(){actorPicker=new MV.admin.common.RelationshipPicker("episodeActors",actors,{cast:true,placeholder:"Search actors…"});directorPicker=new MV.admin.common.RelationshipPicker("episodeDirectors",directors,{placeholder:"Search directors…"});writerPicker=new MV.admin.common.RelationshipPicker("episodeWriters",writers,{placeholder:"Search writers…"});MV.admin.common.bindImagePreview(document.getElementById("Image"),document.getElementById("episodePreview"),{label:"Episode image"});}
  function fill(ep){const set=(n,v)=>{if(form.elements[n])form.elements[n].value=v??"";};set("Title",ep.title);set("EpisodeNumber",ep.episodeNumber);set("Description",ep.description);set("ReleaseDate",MV.admin.common.dateInput(ep.releaseDate));set("RuntimeMinutes",ep.runtimeMinutes);document.getElementById("episodePreview").src=MV.media.imageUrl(ep.imageUrl,true);actorPicker.setSelected(ep.cast||[]);directorPicker.setSelected(ep.directors||[]);writerPicker.setSelected(ep.writers||[]);}
  function setupValidation(){$(form).validate({rules:{Title:{required:true,maxlength:300},EpisodeNumber:{required:true,min:1},RuntimeMinutes:{min:1}},messages:{Title:{required:"Episode title is required.",maxlength:"Episode title cannot exceed 300 characters."},EpisodeNumber:{required:"Episode number is required.",min:"Episode number must be greater than 0."},RuntimeMinutes:{min:"Runtime must be greater than 0."}},submitHandler:submit});}
  async function submit(){const cast=actorPicker.castValues();if(!MV.admin.common.validateCast(cast))return;const file=document.getElementById("Image").files?.[0];if(file&&!MV.admin.common.validateImage(file,"Episode image"))return;const fd=new FormData(form);MV.admin.common.addCast(fd,"Actors",cast);MV.admin.common.addList(fd,"DirectorIds",directorPicker.ids());MV.admin.common.addList(fd,"WriterIds",writerPicker.ids());MV.ui.buttonBusy(saveBtn,true,"Saving…");try{if(id){await MV.api.put(`episodes/${id}`,fd);MV.ui.setFlash("Episode updated","success");}else{await MV.api.post(`seasons/${seasonId}/episodes`,fd);MV.ui.setFlash("Episode created","success");}location.href=season?.tvShowId?`tvshow-form.html?id=${season.tvShowId}`:"tvshows.html";}catch(err){MV.ui.showError(err);}finally{MV.ui.buttonBusy(saveBtn,false);}}
});
