document.addEventListener("DOMContentLoaded",async()=>{
  if(!MV.auth.isAdmin())return;const params=new URLSearchParams(location.search),type=params.get("type"),id=params.get("id");if(!["actor","director","writer"].includes(type)){location.replace("actors.html");return;}const form=document.getElementById("personForm"),saveBtn=document.getElementById("savePerson"),label=type.charAt(0).toUpperCase()+type.slice(1);document.getElementById("personFormTitle").textContent=id?`Edit ${label}`:`Create ${label}`;document.querySelectorAll(".js-person-label").forEach(x=>x.textContent=label);document.getElementById("personBackLink").href=`${type}s.html`;
  MV.admin.common.bindImagePreview(document.getElementById("ProfileImage"),document.getElementById("personPreview"),{label:"Profile image",kind:"people"});
  if(id){try{fill(await MV.api.get(`${type}s/${id}`));}catch(err){MV.ui.showError(err);}}
  $.validator.addMethod("notFuture",v=>!v||new Date(v)<=new Date(),"Date cannot be in the future.");$.validator.addMethod("deathAfterBirth",v=>!v||!form.elements.BirthDate.value||new Date(v)>new Date(form.elements.BirthDate.value),"Death date must be after birth date.");
  $(form).validate({rules:{FullName:{required:true,maxlength:200},HeightInMeters:{min:0.01},BirthDate:{notFuture:true},DeathDate:{notFuture:true,deathAfterBirth:true}},messages:{FullName:{required:`${label} name is required.`,maxlength:`${label} name cannot exceed 200 characters.`},HeightInMeters:{min:"Height must be greater than 0."}},submitHandler:submit});
  function fill(p){for(const name of ["FullName","Biography","BirthPlace","DeathPlace","HeightInMeters","AlternativeName","Nickname","Spouse","Children","Parents","Relatives","OtherWorks","Trivia","Quote","Trademark"]){if(form.elements[name])form.elements[name].value=MV.ui.optionalText(p[name.charAt(0).toLowerCase()+name.slice(1)]);}form.elements.BirthDate.value=MV.admin.common.dateInput(p.birthDate);form.elements.DeathDate.value=MV.admin.common.dateInput(p.deathDate);const preview=document.getElementById("personPreview");preview.src=MV.media.personImageUrl(p.profileImageUrl,type,true);preview.dataset.mvPlaceholderKind="people";preview.dataset.mvAdminDepth="true";}
  async function submit(){const file=document.getElementById("ProfileImage").files?.[0];if(file&&!MV.admin.common.validateImage(file,"Profile image"))return;const fd=new FormData(form);MV.ui.buttonBusy(saveBtn,true,"Saving…");try{if(id){await MV.api.put(`${type}s/${id}`,fd);MV.ui.setFlash(`${label} updated`,"success");}else{await MV.api.post(`${type}s`,fd);MV.ui.setFlash(`${label} created`,"success");}location.href=`${type}s.html`;}catch(err){MV.ui.showError(err);}finally{MV.ui.buttonBusy(saveBtn,false);}}
});
