<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>774cad2c-9139-4d03-b132-1204c4e29675</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.2.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
      <Folder Include="wwwroot\images\actors\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MovieVerse.Application\MovieVerse.Application.csproj" />
      <ProjectReference Include="..\MovieVerse.Infrastructure\MovieVerse.Infrastructure.csproj" />
    </ItemGroup>

</Project>
